#!/usr/bin/env bash
# Recon a domain name and its subdomains

get_records () {
    answer=$(dig "${1}.$2" | grep "ANSWER SECTION" -A1 | tail -1)
    record=$(echo "$answer" | awk '{print $4}')
    destination=$(echo "$answer" | awk '{print $5}')

    echo "The subdomain $1 is a $record record and points to $destination"
}

subs=("www" "lb-01" "web-01" "web-02")

if [ "$#" -le 1 ]; then
    for sub in "${subs[@]}"
    do
        get_records "$sub" "$1"
    done
else
    for sub in "${@:2}"
    do
        get_records "$sub" "$1"
    done    
fi
