#!/usr/bin/env bash
#script that transfers a file to a server using scp

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
    scp "$1" "$3@$2":~/
else
    scp "$1" "$3@$2":~/ -i "$4"
fi
