#!/usr/bin/env bash
# Install HAproxy

apt-get update
apt-get -y install haproxy

configuration=\
"
frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend nginx_webservers

backend nginx_webservers
    balance roundrobin
    server 276248-web-01	34.232.71.74:80 check
    server 276248-web-02	100.25.34.189:80 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
